#!/bin/bash

usage() {
	cat << EOF
git-browse will use the remote.origin.url to calculate the website for the current repository
and open it in a browser
EOF
exit 1
}

while getopts 'h' c
do
  case $c in
    h) usage ;;
  esac
done

# Remove the parameters
shift $((OPTIND-1))

origin=$(git config --get remote.origin.url | sed 's/ //g')
main=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')

if [[ $origin =~ ^git@ ]] ; then
	origin=$(echo "$origin" | sed 's#:#/#' | sed 's#git@#https://#' | sed 's/\.git//')
fi

repo=$(basename $origin)
cwd=$(pwd | sed "s#.*/$repo##" | sed "s#/##")
url="$origin/tree/$main/$cwd"
open $url
